#include "UrvPaths.h"

#include "CesiumGeoreference.h"
#include "DrawDebugHelpers.h"
#include "Materials/MaterialInstanceDynamic.h"
#include "Materials/MaterialInterface.h"
#include "ProceduralMeshComponent.h"
#include "Engine/Engine.h"
#include "Engine/GameViewportClient.h"
#include "Engine/World.h"
#include "GameFramework/PlayerController.h"
#include "Camera/PlayerCameraManager.h"
#include "UrvDirector.h"
#include "UrvTypes.h"

namespace
{
	FString Key(int32 Entity, const FString& Name) { return FString::Printf(TEXT("%d/%s"), Entity, *Name); }

	// 0 green, 0.5 amber, 1 red.
	FLinearColor Heat(double K)
	{
		K = FMath::Clamp(K, 0.0, 1.0);
		const FLinearColor G(0.20f, 0.85f, 0.40f), A(1.00f, 0.72f, 0.15f), R(1.00f, 0.25f, 0.20f);
		return K < 0.5 ? FLinearColor::LerpUsingHSV(G, A, float(K * 2.0)) : FLinearColor::LerpUsingHSV(A, R, float(K * 2.0 - 1.0));
	}
}

AUrvPaths::AUrvPaths()
{
	PrimaryActorTick.bCanEverTick = true;
	PrimaryActorTick.TickGroup = TG_PostUpdateWork;   // after the director has placed the vehicles and the camera moved
	Mesh = CreateDefaultSubobject<UProceduralMeshComponent>(TEXT("Ribbons"));
	Mesh->SetCastShadow(false);
	Mesh->SetCollisionEnabled(ECollisionEnabled::NoCollision);
	Mesh->bUseAsyncCooking = false;
	RootComponent = Mesh;
}

void AUrvPaths::BeginPlay()
{
	Super::BeginPlay();
	// Generated by Tools/make_materials.py; without it the paths fall back to plain debug lines.
	UMaterialInterface* Base = LoadObject<UMaterialInterface>(nullptr, TEXT("/UnrealRocketViz/Materials/M_UrvPath.M_UrvPath"), nullptr,
		LOAD_NoWarn | LOAD_Quiet);
	if (Base)
	{
		// The scene is exposed for daylight: emissive needs nits on that scale to glow at all.
		constexpr float DaylightNits = 2000.0f;
		RibbonMaterial = UMaterialInstanceDynamic::Create(Base, this);
		RibbonMaterial->SetScalarParameterValue(TEXT("Intensity"), Glow * DaylightNits);
	}
	else
	{
		UE_LOG(LogTemp, Warning, TEXT("UnrealRocketViz: M_UrvPath missing (run Tools/make_materials.py); paths drawn as plain lines"));
	}
}

namespace
{
	const TCHAR* ModeName(EUrvPathMode M)
	{
		return M == EUrvPathMode::Current ? TEXT("CURRENT") : M == EUrvPathMode::WithGhosts ? TEXT("WITH EARLIER PLANS") : TEXT("HIDDEN");
	}

	void Notice(const FString& Text)
	{
		UE_LOG(LogTemp, Log, TEXT("UnrealRocketViz: %s"), *Text);
		if (GEngine)
		{
			GEngine->AddOnScreenDebugMessage(0x55525650, 2.0f, FColor::White, Text);
		}
	}
}

void AUrvPaths::PushPath(uint32 SenderId, int32 EntityId, const FString& Name, uint32 Version, double SimTime,
	TArray<FVector> PointsEcef)
{
	FScopeLock ScopeLock(&Lock);
	if (SenderId != Sender)
	{
		Sender = SenderId;
		Pending.Reset();
		Latest.Reset();
		bSenderChanged = true;
	}
	const FString K = Key(EntityId, Name);
	if (const uint32* Have = Latest.Find(K))
	{
		if (Version <= *Have)
		{
			return;   // a repeat (sent again in case of loss) or a late one
		}
	}
	Latest.Add(K, Version);
	Pending.Add({EntityId, Name, Version, SimTime, MoveTemp(PointsEcef)});
}

void AUrvPaths::CyclePathMode()
{
	PathMode = static_cast<EUrvPathMode>((static_cast<uint8>(PathMode) + 1) % 3);
	Notice(FString::Printf(TEXT("PATHS: %s (%d shown)"), ModeName(PathMode), Shown.Num()));
}

void AUrvPaths::ToggleTrail()
{
	bShowTrail = !bShowTrail;
	int32 N = 0;
	for (const TPair<int32, TArray<FTrailPoint>>& Tr : Trails)
	{
		N += Tr.Value.Num();
	}
	Notice(FString::Printf(TEXT("TRAIL: %s (%d points)"), bShowTrail ? TEXT("ON") : TEXT("OFF"), N));
}

const FUrvPathStyle& AUrvPaths::StyleFor(const FString& Name) const
{
	static const FUrvPathStyle Default;
	const FUrvPathStyle* S = Styles.FindByPredicate([&Name](const FUrvPathStyle& X) { return X.Name == Name; });
	return S ? *S : Default;
}

void AUrvPaths::ClearShown()
{
	Shown.Reset();
	Trails.Reset();
	LastTrailT = -1e300;
}

void AUrvPaths::Tick(float DeltaSeconds)
{
	Super::Tick(DeltaSeconds);
	const FUrvFrame* F = Director ? Director->GetDisplayFrame() : nullptr;
	if (!F || !Director->Georeference)
	{
		return;
	}
	const double T = F->SimTime;
	if (T < LastDisplayT - 1.0)
	{
		ClearShown();   // the sender started a new run
	}
	LastDisplayT = T;

	// Paths whose time has come on the display clock.
	{
		FScopeLock ScopeLock(&Lock);
		if (bSenderChanged)
		{
			ClearShown();
			bSenderChanged = false;
		}
		for (int32 i = 0; i < Pending.Num();)
		{
			if (Pending[i].SimTime <= T)
			{
				UE_LOG(LogTemp, Verbose, TEXT("UnrealRocketViz: path '%s' v%u, %d points"), *Pending[i].Name, Pending[i].Version,
					Pending[i].Ecef.Num());
				if (Shown.Num() == 0)
				{
					UE_LOG(LogTemp, Log, TEXT("UnrealRocketViz: first path '%s' (%d points)"), *Pending[i].Name, Pending[i].Ecef.Num());
				}
				Shown.Add(MoveTemp(Pending[i]));
				Pending.RemoveAt(i);
			}
			else
			{
				++i;
			}
		}
	}
	// Keep the newest Ghosts + 1 per (entity, name).
	for (int32 i = Shown.Num() - 1; i >= 0; --i)
	{
		int32 Newer = 0;
		for (int32 j = i + 1; j < Shown.Num(); ++j)
		{
			Newer += (Shown[j].Entity == Shown[i].Entity && Shown[j].Name == Shown[i].Name) ? 1 : 0;
		}
		if (Newer > StyleFor(Shown[i].Name).Ghosts)
		{
			Shown.RemoveAt(i);
		}
	}

	// The flown trail, sampled from what is displayed.
	if (T < LastTrailT || T - LastTrailT >= TrailSpacing)
	{
		LastTrailT = T;
		for (const FUrvEntityState& E : F->Entities)
		{
			TArray<FTrailPoint>& Tr = Trails.FindOrAdd(E.Id);
			const double* V = TrailChannel.IsNone() ? nullptr : E.Channels.Find(TrailChannel);
			Tr.Add({E.PosEcef, V ? *V : 0.0, V != nullptr});
			if (Tr.Num() > TrailMaxPoints)
			{
				Tr.RemoveAt(0, Tr.Num() - TrailMaxPoints);
			}
		}
	}
	Draw(*F);
}

namespace
{
	// Camera-facing strips for M_UrvPath. Vertex colour = colour and opacity; UV0 = (metres along, 0..1
	// across); UV1 = (flow: pulses travel toward the end, core weight).
	struct FRibbons
	{
		TArray<FVector> V;
		TArray<int32> Tri;
		TArray<FVector2D> UV0, UV1;
		TArray<FLinearColor> C;
		FVector Cam = FVector::ZeroVector;
		double PixelAt1 = 0.001;   // world size of one pixel at unit distance

		double HalfWidth(const FVector& P, double Px) const { return 0.5 * Px * FVector::Dist(Cam, P) * PixelAt1; }

		void Quad(int32 A0, int32 B0, int32 A1, int32 B1)
		{
			Tri.Append({A0, B0, A1, B0, B1, A1});
		}

		// A polyline facing the camera; Colour(i) per point.
		template <typename FColourAt>
		void Strip(const TArray<FVector>& W, double Px, float Flow, float Core, FColourAt Colour)
		{
			if (W.Num() < 2)
			{
				return;
			}
			double S = 0.0;
			FVector Side = FVector::UpVector;
			for (int32 i = 0; i < W.Num(); ++i)
			{
				const FVector Tan = (W[FMath::Min(i + 1, W.Num() - 1)] - W[FMath::Max(i - 1, 0)]).GetSafeNormal();
				const FVector Cross = FVector::CrossProduct(Tan, (Cam - W[i]).GetSafeNormal());
				if (Cross.SizeSquared() > 1e-8)
				{
					Side = Cross.GetSafeNormal();
				}
				if (i > 0)
				{
					S += FVector::Dist(W[i - 1], W[i]) / 100.0;
				}
				const double H = HalfWidth(W[i], Px);
				const int32 Base = V.Num();
				V.Add(W[i] - Side * H);
				V.Add(W[i] + Side * H);
				UV0.Add(FVector2D(S, 0.0));
				UV0.Add(FVector2D(S, 1.0));
				UV1.Add(FVector2D(Flow, Core));
				UV1.Add(FVector2D(Flow, Core));
				const FLinearColor Col = Colour(i);
				C.Add(Col);
				C.Add(Col);
				if (i > 0)
				{
					Quad(Base - 2, Base - 1, Base, Base + 1);
				}
			}
		}

		// A flat ring around Centre in the plane normal to Up, of on-screen width Px.
		void Ring(const FVector& Centre, const FVector& Up, double RadiusCm, double Px, const FLinearColor& Col)
		{
			const FVector X = FVector::CrossProduct(Up, FMath::Abs(Up.Z) < 0.9 ? FVector::UpVector : FVector::ForwardVector).GetSafeNormal();
			const FVector Y = FVector::CrossProduct(Up, X);
			const double H = HalfWidth(Centre, Px);
			constexpr int32 N = 64;
			for (int32 k = 0; k <= N; ++k)
			{
				const double A = 2.0 * PI * k / N;
				const FVector R = X * FMath::Cos(A) + Y * FMath::Sin(A);
				const int32 Base = V.Num();
				V.Add(Centre + R * (RadiusCm - H));
				V.Add(Centre + R * (RadiusCm + H));
				UV0.Add(FVector2D(A * RadiusCm / 100.0, 0.0));
				UV0.Add(FVector2D(A * RadiusCm / 100.0, 1.0));
				UV1.Add(FVector2D(0.0, 1.0));
				UV1.Add(FVector2D(0.0, 1.0));
				C.Add(Col);
				C.Add(Col);
				if (k > 0)
				{
					Quad(Base - 2, Base - 1, Base, Base + 1);
				}
			}
		}
	};

	FLinearColor WithAlpha(FLinearColor C, float A)
	{
		C.A = A;
		return C;
	}
}

void AUrvPaths::Draw(const FUrvFrame& F)
{
	Mesh->ClearAllMeshSections();
	if (PathMode == EUrvPathMode::Hidden && !bShowTrail)
	{
		return;
	}
	ACesiumGeoreference* Geo = Director->Georeference;
	const FVector Offset = Director->GetGroundOffset();
	auto ToWorld = [Geo, &Offset](const FVector& Ecef) { return Geo->TransformEarthCenteredEarthFixedPositionToUnreal(Ecef) + Offset; };

	FRibbons R;
	if (const APlayerController* PC = GetWorld()->GetFirstPlayerController())
	{
		if (PC->PlayerCameraManager)
		{
			R.Cam = PC->PlayerCameraManager->GetCameraLocation();
			FVector2D Viewport(1920.0, 1080.0);
			if (GEngine && GEngine->GameViewport)
			{
				GEngine->GameViewport->GetViewportSize(Viewport);
			}
			const double HalfFov = FMath::DegreesToRadians(PC->PlayerCameraManager->GetFOVAngle() * 0.5);
			R.PixelAt1 = 2.0 * FMath::Tan(HalfFov) / FMath::Max(Viewport.X, 1.0);
		}
	}
	const double Now = GetWorld()->GetTimeSeconds();

	if (PathMode != EUrvPathMode::Hidden)
	{
		for (int32 i = 0; i < Shown.Num(); ++i)
		{
			const FPath& P = Shown[i];
			int32 Age = 0;   // 0: the newest of its kind
			for (int32 j = i + 1; j < Shown.Num(); ++j)
			{
				Age += (Shown[j].Entity == P.Entity && Shown[j].Name == P.Name) ? 1 : 0;
			}
			if ((Age > 0 && PathMode != EUrvPathMode::WithGhosts) || P.Ecef.Num() < 2)
			{
				continue;
			}
			const FUrvPathStyle& S = StyleFor(P.Name);
			const FLinearColor Light = FLinearColor::LerpUsingHSV(S.Color, FLinearColor::White, Pastel);
			TArray<FVector> W;
			W.Reserve(P.Ecef.Num());
			for (const FVector& E : P.Ecef)
			{
				W.Add(ToWorld(E));
			}
			if (Age > 0)
			{
				// An earlier plan: a faint, thin, cooler line.
				const FLinearColor G = WithAlpha(FLinearColor::LerpUsingHSV(Light, FLinearColor(0.7f, 0.75f, 0.82f), 0.5f),
					0.4f * Opacity / float(Age));
				R.Strip(W, 0.45 * LinePixels, 0.0f, 0.6f, [&G](int32) { return G; });
				continue;
			}
			// The newest: dim where the vehicle has already been, bright ahead, pulses toward the end.
			int32 Here = 0;
			if (const FUrvEntityState* E = F.Find(P.Entity))
			{
				double Best = TNumericLimits<double>::Max();
				for (int32 k = 0; k < P.Ecef.Num(); ++k)
				{
					const double D = FVector::DistSquared(P.Ecef[k], E->PosEcef);
					if (D < Best)
					{
						Best = D;
						Here = k;
					}
				}
			}
			const FLinearColor Col = Light;
			const float Op = Opacity;
			R.Strip(W, LinePixels, S.bDashed ? 0.0f : 1.0f, 1.0f, [&Col, Here, Op](int32 k) {
				return WithAlpha(Col, k < Here ? 0.2f * Op : Op);
			});
			// The end of the plan (e.g. the landing target): a ring and a slow outgoing pulse.
			const FVector End = W.Last();
			const FVector Up = Geo->TransformEarthCenteredEarthFixedDirectionToUnreal(P.Ecef.Last().GetSafeNormal()).GetSafeNormal();
			const double Ph = FMath::Fmod(Now, 2.0) / 2.0;
			R.Ring(End + Up * 30.0, Up, 900.0, 0.5 * LinePixels, WithAlpha(Col, Op));
			R.Ring(End + Up * 30.0, Up, 900.0 + 2600.0 * Ph, 0.35 * LinePixels, WithAlpha(Col, float(0.6 * Op * (1.0 - Ph))));
		}
	}

	if (bShowTrail)
	{
		for (const TPair<int32, TArray<FTrailPoint>>& Tr : Trails)
		{
			const TArray<FTrailPoint>& Pts = Tr.Value;
			TArray<FVector> W;
			W.Reserve(Pts.Num());
			for (const FTrailPoint& P : Pts)
			{
				W.Add(ToWorld(P.Ecef));
			}
			const double Max = TrailMax;
			const int32 N = Pts.Num();
			const float Pa = Pastel, Op = Opacity;
			R.Strip(W, 0.7 * LinePixels, 0.0f, 0.55f, [&Pts, Max, N, Pa, Op](int32 k) {
				const FTrailPoint& P = Pts[k];
				const FLinearColor Base = P.bHasValue && Max > 0.0 ? Heat(P.Value / Max) : FLinearColor(0.9f, 0.92f, 0.95f);
				const float Age = N > 1 ? float(k) / float(N - 1) : 1.0f;   // 0 oldest, 1 newest
				return WithAlpha(FLinearColor::LerpUsingHSV(Base, FLinearColor::White, Pa), Op * (0.06f + 0.9f * Age * Age));
			});
		}
	}

	if (R.V.Num() == 0)
	{
		return;
	}
	if (RibbonMaterial)
	{
		Mesh->CreateMeshSection_LinearColor(0, R.V, R.Tri, TArray<FVector>(), R.UV0, R.UV1, TArray<FVector2D>(),
			TArray<FVector2D>(), R.C, TArray<FProcMeshTangent>(), false);
		Mesh->SetMaterial(0, RibbonMaterial);
		return;
	}
	// No ribbon material yet: the centre lines, one frame each.
	UWorld* World = GetWorld();
	for (int32 t = 0; t + 5 < R.Tri.Num(); t += 6)
	{
		const FVector A = 0.5 * (R.V[R.Tri[t]] + R.V[R.Tri[t + 1]]);
		const FVector B = 0.5 * (R.V[R.Tri[t + 2]] + R.V[R.Tri[t + 4]]);
		const double D = FVector::Dist(R.Cam, 0.5 * (A + B));
		DrawDebugLine(World, A, B, R.C[R.Tri[t + 2]].ToFColor(true), false, -1.0f, SDPG_World, float(2.0 * D * R.PixelAt1));
	}
}
