#include "UrvVehicle.h"

#include "Components/PointLightComponent.h"
#include "Components/StaticMeshComponent.h"
#include "Materials/MaterialInstanceDynamic.h"
#include "UObject/ConstructorHelpers.h"

namespace
{
	constexpr double CmPerM = 100.0;
	// Emissive is in nits. Under CesiumSunSky's physical sun the exposure sits near
	// daylight, so a flame has to be thousands of times brighter than a lamp to read.
	constexpr float DaylightNits = 2000.0f;
	const FLinearColor Charcoal(0.035f, 0.037f, 0.04f);
	const FLinearColor Gunmetal(0.12f, 0.12f, 0.13f);
	// Basic shapes are 1 m along their Z axis and centred (cone tip at +Z).
	const FRotator TipForward(-90.0, 0.0, 0.0);
	const FRotator TipAft(90.0, 0.0, 0.0);

	// Generated by Tools/make_materials.py; engine materials are the fallback.
	UMaterialInterface* LoadPluginMaterial(const TCHAR* Path)
	{
		return LoadObject<UMaterialInterface>(nullptr, Path, nullptr, LOAD_NoWarn | LOAD_Quiet);
	}

	UMaterialInstanceDynamic* MakePlumeMid(UMaterialInterface* Base, UObject* Outer, float Intensity, const FLinearColor& Tail)
	{
		UMaterialInstanceDynamic* Mid = UMaterialInstanceDynamic::Create(Base, Outer);
		Mid->SetScalarParameterValue(TEXT("Intensity"), Intensity);
		Mid->SetVectorParameterValue(TEXT("TailColor"), Tail);
		return Mid;
	}
}

AUrvVehicle::AUrvVehicle()
{
	PrimaryActorTick.bCanEverTick = false;
	Root = CreateDefaultSubobject<USceneComponent>(TEXT("Root"));
	RootComponent = Root;

	static ConstructorHelpers::FObjectFinder<UStaticMesh> CylinderF(TEXT("/Engine/BasicShapes/Cylinder.Cylinder"));
	static ConstructorHelpers::FObjectFinder<UStaticMesh> ConeF(TEXT("/Engine/BasicShapes/Cone.Cone"));
	static ConstructorHelpers::FObjectFinder<UStaticMesh> CubeF(TEXT("/Engine/BasicShapes/Cube.Cube"));
	static ConstructorHelpers::FObjectFinder<UMaterialInterface> PlumeF(TEXT("/Engine/EngineMaterials/EmissiveMeshMaterial.EmissiveMeshMaterial"));
	static ConstructorHelpers::FObjectFinder<UMaterialInterface> HullF(TEXT("/Engine/BasicShapes/BasicShapeMaterial.BasicShapeMaterial"));
	Cylinder = CylinderF.Object;
	Cone = ConeF.Object;
	Cube = CubeF.Object;
	PlumeMaterial = LoadPluginMaterial(TEXT("/UnrealRocketViz/Materials/M_UrvPlume.M_UrvPlume"));
	HullMaterial = LoadPluginMaterial(TEXT("/UnrealRocketViz/Materials/M_UrvHull.M_UrvHull"));
	if (!PlumeMaterial)
	{
		PlumeMaterial = PlumeF.Object;
	}
	if (!HullMaterial)
	{
		HullMaterial = HullF.Object;
	}
}

UStaticMeshComponent* AUrvVehicle::AddMesh(UStaticMesh* Mesh, const FVector& CenterM, const FVector& SizeM, const FRotator& Rot)
{
	UStaticMeshComponent* C = NewObject<UStaticMeshComponent>(this);
	C->SetupAttachment(Root);
	C->SetStaticMesh(Mesh);
	C->SetRelativeLocation(CenterM * CmPerM);
	C->SetRelativeRotation(Rot);
	C->SetRelativeScale3D(SizeM);
	C->SetMaterial(0, HullMaterial);
	C->SetCollisionEnabled(ECollisionEnabled::NoCollision);
	C->RegisterComponent();
	return C;
}

void AUrvVehicle::Paint(UStaticMeshComponent* C, const FLinearColor& Color, float Roughness)
{
	UMaterialInstanceDynamic* Mid = UMaterialInstanceDynamic::Create(HullMaterial, this);
	Mid->SetVectorParameterValue(TEXT("BaseColor"), Color);
	Mid->SetScalarParameterValue(TEXT("Roughness"), Roughness);
	C->SetMaterial(0, Mid);
}

void AUrvVehicle::Build(const FUrvStageLook& InLook)
{
	Look = InLook;
	const double X0 = Look.StartX, D = Look.Diameter;
	AddMesh(Cylinder, FVector(X0 + Look.Length / 2, 0, 0), FVector(D, D, Look.Length), TipForward);
	if (Look.NoseLength > 0.0)
	{
		AddMesh(Cone, FVector(X0 + Look.Length + Look.NoseLength / 2, 0, 0), FVector(D, D, Look.NoseLength), TipForward);
	}
	for (int32 i = 0; i < Look.Fins; ++i)
	{
		const FRotator Roll(0.0, 0.0, 360.0 / Look.Fins * i);
		const FVector Out = Roll.RotateVector(FVector(0, 0, D / 2 + 0.3 * D));
		UStaticMeshComponent* Fin = AddMesh(Cube, FVector(X0 + 0.08 * Look.Length, 0, 0) + Out,
			FVector(0.16 * Look.Length, 0.04 * D, 0.6 * D), FRotator::ZeroRotator);
		Fin->SetRelativeRotation(Roll);
	}
	const double B = Look.BellDiameter;
	Paint(AddMesh(Cone, FVector(X0 - B / 2, 0, 0), FVector(B, B, B), TipForward), Gunmetal, 0.25f);

	// Livery: dark engine section and a dark band at the top joint.
	const double Skirt = FMath::Min(0.12 * Look.Length, 2.5);
	Paint(AddMesh(Cylinder, FVector(X0 + Skirt / 2, 0, 0), FVector(D * 1.01, D * 1.01, Skirt), TipForward), Charcoal, 0.6f);
	const double Band = FMath::Min(0.06 * Look.Length, 1.2);
	Paint(AddMesh(Cylinder, FVector(X0 + Look.Length - Band / 2, 0, 0), FVector(D * 1.01, D * 1.01, Band), TipForward), Charcoal, 0.6f);

	PlumeMid = MakePlumeMid(PlumeMaterial, this, 25.0f * DaylightNits, FLinearColor(1.0f, 0.38f, 0.06f));
	CoreMid = MakePlumeMid(PlumeMaterial, this, 60.0f * DaylightNits, FLinearColor(1.0f, 0.75f, 0.3f));
	Plume = AddMesh(Cone, FVector::ZeroVector, FVector::OneVector, TipAft);
	PlumeCore = AddMesh(Cone, FVector::ZeroVector, FVector::OneVector, TipAft);
	Plume->SetMaterial(0, PlumeMid);
	PlumeCore->SetMaterial(0, CoreMid);
	for (UStaticMeshComponent* P : { Plume.Get(), PlumeCore.Get() })
	{
		P->SetCastShadow(false);
		P->SetVisibility(false);
	}

	Glow = NewObject<UPointLightComponent>(this);
	Glow->SetupAttachment(Root);
	Glow->SetRelativeLocation(FVector(X0 - B - 3.0, 0, 0) * CmPerM);
	Glow->SetLightColor(FLinearColor(1.0f, 0.75f, 0.45f));
	Glow->SetAttenuationRadius(8000.0f);
	Glow->SetIntensity(0.0f);
	Glow->RegisterComponent();
}

void AUrvVehicle::SetEngine(bool bOn, double AltitudeM)
{
	if (!Plume)
	{
		return;
	}
	Plume->SetVisibility(bOn);
	PlumeCore->SetVisibility(bOn);
	Glow->SetIntensity(bOn ? 2.0e6f : 0.0f);
	if (!bOn)
	{
		return;
	}
	const double Thin = FMath::Clamp(AltitudeM / 40000.0, 0.0, 1.0);
	const double Length = Look.PlumeLength * (1.0 + Look.PlumeVacuumLength * Thin) * (1.0 + 0.04 * FMath::FRand());
	const double Width = 0.92 * Look.BellDiameter;   // the root never spills past the nozzle lip
	const double Nozzle = Look.StartX - Look.BellDiameter;
	Plume->SetRelativeLocation(FVector(Nozzle - Length / 2, 0, 0) * CmPerM);
	Plume->SetRelativeScale3D(FVector(Width, Width, Length));

	// Inner core: short and narrow, inside the outer plume.
	const double CoreLength = 0.35 * Length;
	const double CoreWidth = 0.6 * Look.BellDiameter;
	PlumeCore->SetRelativeLocation(FVector(Nozzle - CoreLength / 2, 0, 0) * CmPerM);
	PlumeCore->SetRelativeScale3D(FVector(CoreWidth, CoreWidth, CoreLength));

	// Vacuum: paler, bluer, more diffuse. Shock diamonds only in dense air.
	const float Vacuum = static_cast<float>(FMath::Clamp(AltitudeM / 60000.0, 0.0, 1.0));
	const float Diamonds = static_cast<float>(1.0 - FMath::Clamp(AltitudeM / 15000.0, 0.0, 1.0));
	for (UMaterialInstanceDynamic* Mid : { PlumeMid.Get(), CoreMid.Get() })
	{
		Mid->SetScalarParameterValue(TEXT("Vacuum"), Vacuum);
		Mid->SetScalarParameterValue(TEXT("Diamonds"), Diamonds);
	}
}
